### ISSUE TITLE
Repo key expired yesterday

### ISSUE THREAD

**Issue by grvn** [mattermost/mattermost-omnibus#102]
The repo key ( https://deb.packages.mattermost.com/pubkey.gpg ) expired yesterday and the repo needs a resign.

```
/etc/apt/trusted.gpg.d/mattermost.gpg
-------------------------------------
pub   rsa2048 2017-03-27 [SC] [expired: 2024-04-06]
      A1B3 1D46 F0F3 A10B 02CF  2D44 F8F2 C317 4477 4B28
uid           [ expired] Mattermost Build <dev-ops@mattermost.com>
```

**Comment by seynard** [comment]
Any news? this key issue is quite annoying as it's blocking my system to fully update properly ... I hope that a new key will be provided soon. Cheers :)

**Comment by raoulh** [comment]
Hey mattermost-devs, it's been 2 weeks now that the key expired.
Please update!

**Comment by winmasta** [comment]
Same problem

**Comment by phoinixgrr** [comment]
Related to: https://github.com/mattermost/desktop/issues/3000

Do find available documentation on https://docs.mattermost.com/install/installing-mattermost-omnibus.html#add-the-mattermost-ppa-repositories on how to update the key.
