### ISSUE TITLE
systemd service file After setting

### ISSUE THREAD

**Issue by axu-trex** [mattermost/mattermost-omnibus#113]
#### Summary
The mattermost service might get started before network is ready. If mattermost tries to bind a network socket to a specific IPv6 address, it may randomly fail as that address might not exist on any interface yet.

#### Expected behavior
The `/lib/systemd/system/mattermost.service` file shipped for Ubuntu should have the line `After=network-online.target`.

#### Observed behavior (that appears unintentional) 
The `/lib/systemd/system/mattermost.service` file shipped for ubuntu has the line `After=network.target`.

#### More information
https://systemd.io/NETWORK_ONLINE/

**Comment by agnivade** [comment]
Hi @axu-trex - I transferred your issue to the right repo. Would you be open to create a PR for this? 

The files are https://github.com/mattermost/mattermost-omnibus/blob/09513a8e563bc885ca4a76ce4ccd4fa66410c2d9/mattermost/files/mattermost.service and https://github.com/mattermost/mattermost-omnibus/blob/09513a8e563bc885ca4a76ce4ccd4fa66410c2d9/mmomni/ansible/playbooks/mattermost.service

**Comment by axu-trex** [comment]
Almost forgot about this after my summer holiday. I've now created a pull request: https://github.com/mattermost/mattermost-omnibus/pull/114
