### ISSUE TITLE
No more updates after 6.4.0

### ISSUE THREAD

**Issue by raoulh** [mattermost/mattermost-omnibus#66]
Hi,
I have 2 mattermost servers running with mattermost-omnibus on ubuntu.
The last update was for 6.4.0. But the `https://deb.packages.mattermost.com` repo does not give any more updates.

From your website critical security fixes were released within 6.4.2 and 6.5.0.

`apt update` always says mattermost is up to date. Do you guys still release new versions using omnibus+deb?

**Comment by pfltdv** [comment]
Hi @raoulh , yes we are releasing new versions and looks like we had an issue for generating updates for new new versions. We will investigate and publish missing versions.

**Comment by pfltdv** [comment]
@raoulh, all missing updates are ready now (`6.4.1`, `6.4.2` and `6.5.0`)

![image](https://user-images.githubusercontent.com/98656635/160375881-0edfbc86-148a-4b3b-a24e-5514d3f8ea48.png)

**Comment by raoulh** [comment]
Works now, thank you
