### ISSUE TITLE
bash: line 88: curl: command not found

### ISSUE THREAD

**Issue by suciokhan** [mattermost/mattermost-omnibus#67]
First step in the process listed here: https://docs.mattermost.com/install/installing-mattermost-omnibus.html results in an error for me on a fully up-to-date copy of Ubuntu 20.04. I recently removed a standard enterprise edition from my /opt directly via sudo rm -rf mattermost/, if that makes a difference.

I ran this command: `curl -o- https://deb.packages.mattermost.com/repo-setup.sh | sudo bash` and it seemed to not download anything. I tried it multiple times (showed no progress), and switched broke it into 2 steps:
    - curl -o- https://deb.packages.mattermost.com/repo-setup.sh
    - sudo bash repo-setup.sh

This downloaded the file, but when executing the repo-setup.sh script, I get this error:

`bash: line 88: curl: command not found`

Full execution printout:

```
Executing: /tmp/apt-key-gpghome.5dT6ekYCDY/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys ABF5BD827BD9BF62
gpg: key ABF5BD827BD9BF62: "nginx signing key <signing-key@nginx.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Hit:1 https://updates.signal.org/desktop/apt xenial InRelease
Get:2 http://packages.microsoft.com/repos/code stable InRelease [10.4 kB]                     
Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                     
Hit:4 http://us.archive.ubuntu.com/ubuntu focal InRelease                                     
Hit:5 https://repo.protonvpn.com/debian stable InRelease                                      
Get:6 https://packages.microsoft.com/repos/vscode stable InRelease [3,959 B]                  
Get:7 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                    
Get:8 http://packages.microsoft.com/repos/code stable/main arm64 Packages [77.7 kB]           
Get:9 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]                  
Hit:10 https://nginx.org/packages/ubuntu focal InRelease         
Get:11 https://packages.microsoft.com/repos/vscode stable/main amd64 Packages [292 kB]
Fetched 720 kB in 1s (558 kB/s)    
Reading package lists... Done
N: Skipping acquire of configured file 'nginx/binary-i386/Packages' as repository 'https://nginx.org/packages/ubuntu focal InRelease' doesn't support architecture 'i386'
'universe' distribution component is already enabled for all sources.
repo-setup.sh: line 88: curl: command not found
```
Very odd, considering I just used curl to download the file :S

Hoping it was just a non-breaking glitch, I tried running the next step:

`sudo apt install mattermost-omnibus`

But this results in the following error:

`E: Unable to locate package mattermost-omnibus`

How do I address this curl command not found issue?

**Comment by pfltdv** [comment]
@suciokhan Our script assumes that, curl is already installed in your system. Probably that is the issue. Can you try below ?

```
sudo apt-get install -y curl
curl -o- https://deb.packages.mattermost.com/repo-setup.sh | sudo bash
```

**Comment by pfltdv** [comment]
@suciokhan That is strange, probably with sudo , environment variables may be overwritten. Can you try below ?
```
curl  https://deb.packages.mattermost.com/repo-setup.sh -o repo-setup.sh
chmod +x repo-setup.sh
sudo ./repo-setup.sh
```
-or-
```
curl -o- https://deb.packages.mattermost.com/repo-setup.sh | sudo bash -E
```
