### ISSUE TITLE
Invalid key

### ISSUE THREAD

**Issue by raoulh** [mattermost/mattermost-omnibus#68]
Hey guys,

I suddenly have the following error on my omnibus installations:

```
─➤  apt update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://apt.postgresql.org/pub/repos/apt focal-pgdg InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 https://nginx.org/packages/ubuntu focal InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-security InRelease
Hit:6 https://deb.packages.mattermost.com focal InRelease
Err:6 https://deb.packages.mattermost.com focal InRelease
  The following signatures were invalid: EXPKEYSIG F8F2C31744774B28 Mattermost Build <dev-ops@mattermost.com>
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.packages.mattermost.com focal InRelease: The following signatures were invalid: EXPKEYSIG F8F2C31744774B28 Mattermost Build <dev-ops@mattermost.com>
W: Failed to fetch https://deb.packages.mattermost.com/dists/focal/InRelease  The following signatures were invalid: EXPKEYSIG F8F2C31744774B28 Mattermost Build <dev-ops@mattermost.com>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Did you change you signing key?
I tried to run the `https://deb.packages.mattermost.com/repo-setup.sh` again, but same is happening.

**Comment by ichdasich** [comment]
Same problem here. The signing key used to sign the repo expired:
```
pub   rsa2048 2017-03-27 [SC] [expired: 2022-04-03]
      A1B3 1D46 F0F3 A10B 02CF  2D44 F8F2 C317 4477 4B28
uid           [ expired] Mattermost Build <dev-ops@mattermost.com>

```

**Comment by pfltdv** [comment]
Thank you very much for the feedback, we are currently working on extending our public key.

**Comment by pfltdv** [comment]
@raoulh @ichdasich We resigned our repository and it is healthy as before. If old key still exists in your system you may update keys or you may delete our repo from repolist and execute repo setup script again(curl -o- https://deb.packages.mattermost.com/repo-setup.sh | sudo bash).


```
sudo apt-key remove 44774B28
sudo curl -o- https://deb.packages.mattermost.com/pubkey.gpg | sudo apt-key add -
sudo apt update
```
-or-
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 44774B28
sudo apt update
```

**Comment by ichdasich** [comment]
works, thanks!

**Comment by seynard** [comment]
I know this issue is closed but I'm having the same problem, 
"W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.packages.mattermost.com jammy InRelease: The following signatures were invalid: EXPKEYSIG F8F2C31744774B28 Mattermost Build <dev-ops@mattermost.com>" when doing sudo apt-get update and the fix that you suggested didn't work for me. Would you have anything else in mind to help. 
Cheers

**Comment by grvn** [comment]
@seynard, you're having the same issue as the creator of this issue because it is the same issue.

The same issue happen again.
They need to do a new resign because the current key expired yesterday.
```
/etc/apt/trusted.gpg.d/mattermost.gpg
-------------------------------------
pub   rsa2048 2017-03-27 [SC] [expired: 2024-04-06]
      A1B3 1D46 F0F3 A10B 02CF  2D44 F8F2 C317 4477 4B28
uid           [ expired] Mattermost Build <dev-ops@mattermost.com>
```

**Comment by grvn** [comment]
@seynard - I've created a new issue #102 instead of trying to reopen this one.

**Comment by seynard** [comment]
Hi Richard,

Thanks a lot for reopening this issue.

Best, Sonia

**Comment by winmasta** [comment]
Same problem. Key from [https://deb.packages.mattermost.com/pubkey.gpg](https://deb.packages.mattermost.com/pubkey.gpg)
`
pub   rsa2048 2017-03-27 [SC] [expired: 2028-04-07]
      A1B31D46F0F3A10B02CF2D44F8F2C31744774B28
uid         [ unknown ] Mattermost Build <dev-ops@mattermost.com>
`
